# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-04 02:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.BooleanField(),
        ),
    ]
